// Functions only

import React, { createContext, useContext, useMemo, useEffect } from 'react';
import { useMyState } from './StatesContext';
import { createStopInDB, updateStopsBatch } from '../services/api';
import { minToHHMM } from '../pages/ItinEdit/Parts/Resources/TimeFunc';

interface DashboardContextType {
  totalBudget: number;
  addWaypoint: (insertIndex: number) => Promise<void>;
}

const DashboardContext = createContext<DashboardContextType | undefined>(undefined);

export const DashboardProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  
  const { tempSegments, setTempSegments, tripDetails, calculatedStops, setCalculatedStops, setTotalMiles, setTotalMinutes } = useMyState();

  //BUDGET (Safe to use tempSegments since it doesn't rely on Mapbox)
  const totalBudget = useMemo(() => {
    return (tempSegments ?? []).reduce((runningTotal: number, currentStop: any) => {
      return runningTotal + (Number(currentStop.budget) || 0);
    }, 0);
  }, [tempSegments]);

  // ADD WAYPOINT CRUD
  const addWaypoint = async (insertIndex: number) => {
    if (!tripDetails?.id) return;
    
    const blankStop = {
      trip_id: tripDetails.id,
      sort: insertIndex + 2,
      name: 'New Waypoint',
      lat: null, lng: null,
      stay_time: 0, 
      type: 'stop', 
      note: '', 
      budget: 0, 
      morning_depart: null,
    };

    try {
      const newStopFromDB = await createStopInDB(blankStop);
      const updatedSegments = [...tempSegments];
      updatedSegments.splice(insertIndex + 1, 0, newStopFromDB);
      
      const reSortedSegments = updatedSegments.map((stop, i) => ({ ...stop, sort: i + 1 }));
      setTempSegments(reSortedSegments);
      
      await updateStopsBatch(reSortedSegments);
    } catch (error) {
      console.error("❌ Failed to create waypoint:", error);
    }
  };

  //Manipulate the calculated arrays once the data is generated by mapbox
  useEffect(()=>{
    //Sum all the miles to the trip and set it to the universal time state 
    const miles = calculatedStops.reduce((accumulator, stop)=>{
      const total = Number(stop.drive_to_next_miles) || 0;
      return accumulator + total
    },0)

    //Sum All the minutes to a trip 
    const min = calculatedStops.reduce((accumulator, stop)=>{
      const total = Number(stop.drive_to_next_minutes)||0;
      return accumulator + total;
    },0)
    
    setTotalMinutes(min)
    setTotalMiles(miles);
    //Need to hit a special save for this to update the main db item for total miles and time. 
  },[calculatedStops])

  return (
    <DashboardContext.Provider value={{
      totalBudget,
      addWaypoint
    }}>
      {children}
    </DashboardContext.Provider>
  );
};

export const useDashboard = () => {
  const context = useContext(DashboardContext);
  if (context === undefined) {
    throw new Error('useDashboard must be used within a DashboardProvider');
  }
  return context;
};